---
title: "First Knit"
author: "America Olivo"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
I attended Pete knight high school and I did graduate. I dislike English and I love math. I had a easier understanding on math than english especially because i am not a native Engligh speaker. I like the way math has one answer to a question.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I do have a computer at home it is a HP windows computer. I believe I am a 5 because i am very knowledge but I do lack in a few places including english and logical issues. I do not need internet access. 
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
 I do not mind being called by my first name however I do go by Ame. 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  I want to achieve wealth and successful in my career life. I love science and math and my greatest interest is forensics science. I am trying to achieve a doctorate.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
 Ive only gone to Mexico but I want to go to more foreign countries such as Italy, Japan, and Germany.Ive never been in the military. If I were to choose which branch I would get drafted to I would choose the Air Force (even if i do need glasses) because I would love to fly and fight in the air.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
I have never took a college math course yet and this is my first class. Yes, I do knwo that Math 115 does not qualify for a transferable class to UCs. I would love to get an A in stats but if not I can lvie with a C. I am planning to become a forensic scientist.
   
 






  




